### ISSUE TITLE
ApiException import missing

### ISSUE THREAD

**Issue by Kimmax** [jlevers/selling-partner-api#445]
## Problem description:
API classes seem to be missing the import for `ApiException`.
Version: `5.5.0`

## Error:

For example:
```
PHP Fatal error:  Uncaught Error: Class 'SellingPartnerApi\Api\ApiException' not found in xx/vendor/jlevers/selling-partner-api/lib/Api/TokensV20210301Api.php:87
```

and many more. Adding the include fixes the problem.

**Comment by bigindian66** [comment]
Hello !
I have the same issue here !
Is it ok to add the class manually ?
At least as a workaround until a fix is released ?

B.R.

**Comment by shodanto** [comment]
same problem here

**Comment by steverobison** [comment]
copy the APIException file into the api folder and change its namespace to SellingPartnerApi\Api

**Comment by scabudlan** [comment]
> copy the APIException file into the api folder and change its namespace to SellingPartnerApi\Api. This fixed it for me as a quick fix.
> 
> namespace SellingPartnerApi\Api;

Thank you, the problem is solved.

**Comment by soseki-angfa** [comment]
I guess he wants to use Exception from guzzel client.
Maybe, we wait for that.

**Comment by plegenza** [comment]
Still getting error: "Error: Class 'SellingPartnerApi\Api\ApiException' not found in file /var/www/clients/client0/web4/laravel/vendor/jlevers/selling-partner-api/lib/Api/CatalogItemsV20220401Api.php on line 547"

**Comment by soseki-angfa** [comment]
@plegenza 
This is not fixed yet.
You can just copy the ApiException.php to under Api folder and compile it the namespace.

**Comment by plegenza** [comment]
@soseki-angfa I do that now, thanks. 
Comment by @scabudlan is confusing when for fast reading ;)

**Comment by jlevers** [comment]
Sorry about this guys -- it's fixed in `v5.5.2`.

**Comment by bigindian66** [comment]
Thank you very much for your reactivity !

**Comment by soseki-angfa** [comment]
@jlevers 
Thanks for that.
We really appreciate it.
